# Generated by Django 4.2 on 2025-05-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequirement',
            name='main_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mainworkplan'),
        ),
        migrations.AlterField(
            model_name='addrequirement',
            name='sub_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subworkplan'),
        ),
    ]
