# Generated by Django 4.2 on 2025-05-13 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_addrequirement_main_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='who_rejected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
