# Generated by Django 4.2 on 2025-05-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
    ]
