# Generated by Django 4.2 on 2025-05-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-begin',),
                'unique_together': {('begin', 'end')},
            },
        ),
    ]
