# Generated by Django 4.2 on 2025-05-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.addrequirement'),
        ),
    ]
