# Generated by Django 4.2 on 2025-05-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_sendrequest_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requirement',
            field=models.ForeignKey(blank=True, help_text='Agar hujjat aniq bir reja bandiga javob bersa tanlang.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.addrequirement'),
        ),
    ]
