# Generated by Django 4.2 on 2025-09-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_document_quantity_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequirement',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicyear'),
        ),
        migrations.AddField(
            model_name='planresponse',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicyear'),
        ),
    ]
